### ISSUE TITLE
get_models missing some models?

### ISSUE THREAD

**Issue by merijnman** [ARIA-VALUSPA/AVP#10]
Hi guys,
It looks like some models are missing from the get_models.
Specifically the files missing are: models\speech\*.norm~ 
Cheers!

**Comment by bpotard** [comment]
same as #6 - this has been fixed a couple of weeks ago, pull your git :-)

**Comment by merijnman** [comment]
It is a fresh pull from the public AVP...

**Comment by mvalstar** [comment]
Hi Peter,
I thought the new get_models was in the public release of AVP?

**Comment by bpotard** [comment]
The small models are in the git repository, not downloaded by get_model; they had been removed by mistake for the 3.0 release. They are definitely present in the git repository now!

**Comment by jonlnichols** [comment]
i have the same issue, with the  files that end in ~ being missing  after you guys supposedly fixed it. i figured the issue was with my computer, a windows 7 pc  and was waiting for until i could get a windwos 10 pc to try it on.

**Comment by bpotard** [comment]
ah, you are right, the ~ files are still missing

**Comment by mvalstar** [comment]
Anyone able to commit these? Or should I ask Peter?

**Comment by Barachia** [comment]
Alright, I added the missing models.
