### ISSUE TITLE
Encoding FML with ActiveMQ

### ISSUE THREAD

**Issue by PaulLerner** [ARIA-VALUSPA/AVP#14]
Hello,

I have an issue with the connection with Greta.
I've written FML in french so there are special characters like "é"
If I use Greta FML File reader it works perfectly but if I build a scenario then the FML is sent through eu.aria.util.translator.api.ActiveMQConnector I think and I guess the encoding is wrong because "é" becomes something like "A(c)".

**Comment by Barachia** [comment]
Hi Paul,

I've been able to reproduce the weird encoding. I think you're right about the ActiveMQConnector that something goes wrong there, so I'm gonna look into that.

However, if I use the full system and the Flipper templates and write the characters like é and á there, I am able to send valid FML.

I'll get back to you.

**Comment by PaulLerner** [comment]
You mean that if you change the language to french for example, the agent will actually say "é" and not "A copyright" ?
See the display of the ActiveMQSender here, you'll see that "ça" has turned into "Ã§a"
![fml encoding activemq avp](https://user-images.githubusercontent.com/25532159/42022093-940f2e76-7abc-11e8-910a-b660a52194dd.png)

**Comment by PaulLerner** [comment]
Solution was to add this to the command in the batch file for flipper (start-3-core) : -Dfile.encoding=UTF-8

Thanks @Barachia
