### ISSUE TITLE
StandAlone ASR client fails if webrtcvad is installed (python 3)

### ISSUE THREAD

**Issue by pirelaurent** [ARIA-VALUSPA/AVP#3]
Client run well as long as webrtcvad was not installed (with only the warning message about it.) 
Once webrtcvad installed ( caution pip install webrtcvad needs a valid compiler on windows) , program fails line 116 :   buffer += msg    -> cannot convert 'bytes' object to str implicitly . 
I saw that buffer is initialised as a string buffer = "" , while msg comes from the queue. 

Note: Config is python3.5.2 as indicated in doc.

**Comment by mvalstar** [comment]
Peter, let's see if we can solve this without the help of Eduardo. If you don't know what's going on, let's involve them.

**Comment by g-pechorin** [comment]
I was able to reproduce the error (and more) before fixing this.

It looks like empty strings `""` were being used where `bytes()` would be (strictly speaking) more-correct. 

I've [pushed the changes](https://github.com/ARIA-VALUSPA/AVP/commit/48b72d2c5166d1bcaecbf1b35daafd35d8577ac4)

**Comment by mvalstar** [comment]
Thanks Peter. Pierre, it would be great if you could confirm this solved the issue for you.

**Comment by pirelaurent** [comment]
Yes, thanks. Client runs now with VAD is on. 
I can test a step further.
