### ISSUE TITLE
Launcher agent won't start 

### ISSUE THREAD

**Issue by pirelaurent** [ARIA-VALUSPA/AVP#5]
*start-3-core.bat* starts well and show two windows for activeMqsender & receiver,   
but *start-4-agent.bat* goes wrong with the following :   

    D:\ARIA\ARIA-System>start-4-agent.bat
    Traceback (most recent call last):
     File "launcher.py", line 3, in <module>
     File "c:\program files\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
     File "site-packages\wx\__init__.py", line 17, in <module>
     File "c:\program files\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
     File "site-packages\wx\core.py", line 12, in <module>
    ImportError: No module named 'wx._core'
    Failed to execute script launcher     

I try adding wxpython through :  *pip install wxPython*   ( as administrator)  and this goes well.   
But still the same error with launcher. 
(by the way, launcher only exists in exe, not in source code to debug)

**Comment by bpotard** [comment]
The launcher should not require a system python anyway, so you should not need to install wx with pip on your own. It appears that during the update to 3.0, some launcher files went missing: all the pyd files are gone - which is what this error message is about - and plenty of dll seems to have been added. I think - until this is fixed - if you get the launcher folder from the 2.3 tag it would work.
Maybe we could add the launcher source files here anyway in a "src" subfolder?

**Comment by mvalstar** [comment]
Hmmm. Peter, have you got the launcher files? Clearly they should be included...

**Comment by g-pechorin** [comment]
I've pushed the missing files to `master` so it works. I've checked it on a PC that never had AVP installed before. The software works.

I don't want to call this a 3.0.1 release yet; I'm not happy with the `.gitignore` files since the downloaded models are still showing up. I'll try some other approaches this weekend.

For now; `master` has the missing files and should work.

Peter

**Comment by mvalstar** [comment]
I presume this works. Pierre, feel free to re-open if it doesn't work for you, or create a new issue if you hit a different problem.
